version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=marketplace
  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongodb:27017/marketplace
      - REDIS_URL=redis://redis:6379
      - PORT=5000
      - JWT_SECRET=your_jwt_secret
      - EMAIL_USER=your_email@gmail.com
      - EMAIL_PASS=your_email_password
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./server:/app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://server:5000/api
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
volumes:
  mongodb_data: