name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '6.0'
      - name: Install MongoDB Tools
        run: sudo apt-get update && sudo apt-get install -y mongodb-org-tools
      - name: Install server dependencies
        run: npm install
        working-directory: server
      - name: Restore database
        run: npm run restore
        working-directory: server
        env:
          MONGO_URI: mongodb://127.0.0.1:27017/marketplace
      - name: Run server tests
        run: npm run test
        working-directory: server
      - name: Install client dependencies
        run: npm install
        working-directory: client
      - name: Run client tests
        run: npm test -- --ci
        working-directory: client
